/**
 * RFC 9457 Problem Detail Types
 * Standardized error response format for the Chatbox API
 */

/**
 * Validation error detail for field-level errors
 */
export interface ValidationError {
  /** Field name that failed validation */
  field: string;
  /** Human-readable error message */
  message: string;
}

/**
 * RFC 9457 Problem Detail response
 * @see https://datatracker.ietf.org/doc/html/rfc9457
 */
export interface ProblemDetail {
  /**
   * A URI reference that identifies the problem type
   * When dereferenced, it SHOULD provide human-readable documentation
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type
   * SHOULD NOT change from occurrence to occurrence of the problem
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem
   * Typically the request path
   */
  instance?: string;

  /**
   * Unique identifier for tracking this request
   */
  requestId: string;

  /**
   * Business error code for programmatic handling
   */
  code: string;

  /**
   * Array of validation errors (for 400 Bad Request responses)
   */
  errors?: ValidationError[];
}

/**
 * Error template for creating ProblemDetail responses
 */
export interface ErrorTemplate {
  /** Problem type URI */
  type: string;
  /** Short title */
  title: string;
  /** HTTP status code */
  status: number;
  /** Business error code */
  code: string;
  /** Default detail message */
  detail?: string;
}

/**
 * Mapping of error codes to templates
 */
export type ErrorTemplateMap = Record<string, ErrorTemplate>;
